//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEWEB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaleZdjecie
    {
        public int ID { get; set; }
        public int UzytkownikID { get; set; }
        public Nullable<int> GraID { get; set; }
        public string Tytul { get; set; }
        public System.DateTime DataDodania { get; set; }
        public byte[] PlikGraficzny { get; set; }
    }
}
