//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEWEB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfo
    {
        public string Tytul { get; set; }
        public System.DateTime DataWydania { get; set; }
        public string Opis { get; set; }
        public Nullable<double> SredniaOcena { get; set; }
        public string Studio { get; set; }
    }
}
