//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEWEB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentarze
    {
        public int KomentarzID { get; set; }
        public Nullable<int> WpisID { get; set; }
        public string Tresc { get; set; }
    
        public virtual Wpisy Wpisy { get; set; }
        public virtual Wpisy Wpisy1 { get; set; }
    }
}
