//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEWEB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcenyGier
    {
        public int GraID { get; set; }
        public int UzytkownikID { get; set; }
        public int OcenaOgolna { get; set; }
        public int Fabula { get; set; }
        public int Grafika { get; set; }
    
        public virtual Gry Gry { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
