//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEWEB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ostrzezenia
    {
        public int OstrzezenieID { get; set; }
        public Nullable<int> OstrzegajacyID { get; set; }
        public Nullable<int> OstrzeganyID { get; set; }
        public string Opis { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
        public virtual Uzytkownicy Uzytkownicy1 { get; set; }
    }
}
