//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEWEB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzje
    {
        public int RecenzjaID { get; set; }
        public string DlugaTresc { get; set; }
    
        public virtual Wpisy Wpisy { get; set; }
    }
}
