//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEWEB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uprawnienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uprawnienia()
        {
            this.Uzytkownicy = new HashSet<Uzytkownicy>();
        }
    
        public int UprawnienieID { get; set; }
        public string Nazwa { get; set; }
        public Nullable<bool> DodawanieWpisow { get; set; }
        public Nullable<bool> DodawanieOcen { get; set; }
        public Nullable<bool> UsuwanieWpisowOcen { get; set; }
        public Nullable<bool> UsuwanieWlasnychWpisowOcen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzytkownicy> Uzytkownicy { get; set; }
    }
}
