//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEWEB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzytkownicy()
        {
            this.OcenyGier = new HashSet<OcenyGier>();
            this.OcenyWpisow = new HashSet<OcenyWpisow>();
            this.Ostrzezenia = new HashSet<Ostrzezenia>();
            this.Ostrzezenia1 = new HashSet<Ostrzezenia>();
            this.Wpisy = new HashSet<Wpisy>();
        }
    
        public int UzytkownikID { get; set; }
        public Nullable<int> UprawnienieID { get; set; }
        public string Nazwa { get; set; }
        public string Haslo { get; set; }
        public string Email { get; set; }
        public string Plec { get; set; }
        public bool BlokadaKonta { get; set; }
        public Nullable<System.DateTime> DataUrodzenia { get; set; }
        public byte[] Zdjecie { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenyGier> OcenyGier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenyWpisow> OcenyWpisow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ostrzezenia> Ostrzezenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ostrzezenia> Ostrzezenia1 { get; set; }
        public virtual Uprawnienia Uprawnienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wpisy> Wpisy { get; set; }
    }
}
