//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMEWEB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wpisy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wpisy()
        {
            this.Komentarze1 = new HashSet<Komentarze>();
            this.OcenyWpisow = new HashSet<OcenyWpisow>();
        }
    
        public int WpisID { get; set; }
        public Nullable<int> GraID { get; set; }
        public int UzytkownikID { get; set; }
        public string Tytul { get; set; }
        public System.DateTime DataDodania { get; set; }
    
        public virtual Gry Gry { get; set; }
        public virtual Komentarze Komentarze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komentarze> Komentarze1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenyWpisow> OcenyWpisow { get; set; }
        public virtual Recenzje Recenzje { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
        public virtual Zdjecia Zdjecia { get; set; }
    }
}
